norlab-ulaval/libpointmatcher

pointmatcher/DataPointsFiltersImpl.cpp
I've added support for the Tim3xx laser sensor on the SimpleSensorNoiseDataPointsFilter.
I've obtained the values by taking several readings with the laser sensor stationary. Then, I've obtained mean and standard deviation of each ray. Finally, I've obtained a linear regression (from the linear portion) from plotting std. dev. as a function of the mean. Thus, I had an estimate sensor model which informs error as a function of distance.
Befere 2.5 meters I've estimated a constant error of 0.004m. Afterwards, the line parameters are -0.0092 offset and 0.053 slope.
=> Tim3xx laser support on Simple Noise filter

CMakeLists.txt
Without this the shared library on will be incomplete (have unresolved symbols). This is fine _if_ one correctly (potentially including order!) provides all the missing shared libraries when linking a final executable, which needs to be complete.
This fails for example because the build system is messing up the order of the shared libraries dependencies. For example catkin will produce in unlucky situations a wrong sequence of the shared libraries resulting in a linking error (e.g. undefined libnabo symbols) for the final executable.
Btw: The order constraint for the gnu linker ```ld``` (when invoked with ```--as-needed```, which is default for ```g++``` or ```gcc```) is to have libnabo at least once behind the first libpointmatcher in the list of shared libraries.
=> completed the linking of the shared library

CMakeLists.txt
* introduced EXTRA_DEPS variable to collect targets the pointmatcher target should depend on
* added yam-cpp-pm to EXTRA_DEPS in case of NOT USE_SYSTEM_YAML_CPP
=> addressing #70 by introducing EXTRA_DEPS and adding yam-cpp-pm if necessary

pointmatcher/IO.cpp, pointmatcher/IO.h
* made SupportedLabel CoppyAssignable
* the getSupportedExternalLabels returns now a const reference to the vector rendering the vector of Labels immutable instead
=> addressing issue #78:

contrib/yaml-cpp-pm/CMakeLists.txt
* Fixed missing -pm at one yaml-cpp target reference (for case of MSVC)
=> Adressing #80:

doc/CompilationWindows.md
These are some minor tweaks to the Windows compilation instructions for anyone (like me) less familiar with the toolchain.
Note that I am currently having an SLN generation issue (https://github.com/ethz-asl/libpointmatcher/issues/101) with libpointmatcher itself, so the instructions for the final step should be double-checked for correctness.
=> Make Windows compilation instructions a bit more explicit

pointmatcher/DataPointsFiltersImpl.h, pointmatcher/OutlierFiltersImpl.h
Per https://github.com/ethz-asl/libpointmatcher/issues/113
=> No need to restrict sampling to 0.9999999

README.md, examples/data/default-identity.yaml, pointmatcher/ErrorMinimizersImpl.cpp, pointmatcher/Matches.cpp, utest/utest.cpp
I wiped the previous pull request, and made a new one to be in sync with the latest upstream changes (I could have just appended to that request I guess, but it is cleaner this way).
To summarize, the bug here actually shows up very rarely. I did add a unit test which reproduces it. In order for this issue to show up, one must use point-to-plane alignment, have the two clouds to align be identical, and any filtering which removes points must be turned off. Then, the Eigen::AngleAxis() function cannot create a rotation from a zero vector. The correct rotation is the identity though.
The bug does not show up if one cloud is translated in respect to the other one. Numerical noise results in a non-zero (but very small) rotation matrix.
The bug does not show up either with point-to-point …
=> Handle the degenerate situation when the residuals are 0.

pointmatcher/ErrorMinimizersImpl.cpp
Hi
The SVD in the point matcher can return a reflection instead of a rotation (det=-1 instead of det=1). This later causes the exception "Error, rotation matrix is not orthogonal." due to det(rotationmatrix) = -1.
This fixes it by taking the second best solution of the SVD, guaranteed to be a rotation.
see also: http://igl.ethz.ch/projects/ARAP/svd_rot.pdf
=> fix PointMatcher: SVD can return a reflection instead of a rotation

utest/CMakeLists.txt
Hi
This fixes come unresolved symbols to pthread when linking under Fedora 22.
=> fix compilation of utest, missing pthread library when linking

CMakeLists.txt, pointmatcher.pc.in
The pkg-config file helps external libraries to find and handle this library.
=> Added pkg-config file

CMakeLists.txt
The new one is right above it. So we don't need it. In fact it seems to override the one above.
=> Removed outdated install line that was apparently accidentelly introduced in PR #109 (d199aaaf9).

pointmatcher/ErrorMinimizersImpl.cpp
Hi François
This extends the error minimizer to use weighted least squares minimization. It requires an appropriate OutlierFilter that outputs weights in [0, 1]. With {0, 1} weights, the behavior is unchanged.
- runtime performance similar as before
- unit test passing
- based on: http://igl.ethz.ch/projects/ARAP/svd_rot.pdf (not umeyama 91, this is for the scaling)
=> Weighted error minimizer

pointmatcher/ICP.cpp
In the presence of NaNs in reference data, program crashes even after using RemoveNaNDataPointsFilter since the mean is being calculated on non-filtered data. Also addresses the issue #67.
=> Calculating mean using filtered data to avoid NaNs

pointmatcher/IO.cpp, pointmatcher/IO.h, pointmatcher/IOFunctions.h, pointmatcher/InspectorsImpl.cpp, pointmatcher/InspectorsImpl.h, pointmatcher/PointMatcher.h, utest/ui/IO.cpp
NOT READY to MERGE. 
I just needed faster writing of point clouds and this quick and dirty implementation (not polished for merging yet) is already about 20 times faster than the ASCII version. And e.g. paraview is reading it way faster.
@pomerlef , do you think this is a useful extension (even though it is legacy VTK files anyway and reading the same files would not be supported without further effort) or would you rather switch to libvtk to read and write vtk files. Was there a good reason not to do that in the first place?
=> Support binary VTK legacy files

pointmatcher/ErrorMinimizersImpl.h, pointmatcher/IO.cpp, pointmatcher/IO.h
I clarified the similarity transform, per Francois. And I found what I think is a bug. A typo prevented an input variable from being passed to a class, instead, the class member was assigned to itself. The compiler was complaining.
=> Minor fixes

pointmatcher/ErrorMinimizersImpl.cpp, utest/utest.cpp
Unfortunately it is not clear to me what the right solution for this problem is (see https://github.com/ethz-asl/libpointmatcher/compare/fix/supportSingularICPStepsInPointToPlaneErrorMinimizer?expand=1#diff-51b8a83999c74513d51e6839db229186R188). 
Both suggested ways work nicely for me, though. Maybe a priority (user provided) based algorithm could be the right way.
In https://github.com/ethz-asl/libpointmatcher/compare/fix/supportSingularICPStepsInPointToPlaneErrorMinimizer?expand=1#diff-51b8a83999c74513d51e6839db229186R207 there as a new exception introduced for the case that this does not work. It should cover possible implementation failures. In particular it could be that I guessed wrongly when filling in the specification gaps of Eigen's FullPivHouseholderQr algorithm.
=> Support singular ICP steps in PointToPlane(Cov)ErrorMinimizer

pointmatcher/ErrorMinimizer.cpp, pointmatcher/ErrorMinimizersImpl.cpp, pointmatcher/ErrorMinimizersImpl.h, pointmatcher/PointMatcher.h
I added the getResidualError method to be able to assess the ICP result through the residual error. I'm sharing it here in case you're interested to add the functionality to the library.
Cheers!
----- Begin Commit Message -----
[error minimizer] Add getResidualError methods
getResidualError is a const method and makes use of getMatchedPoints, thus we
also add a const version of getMatchedPoints that does not change
ErrorMinimizer's lastErrorElements.
The residual error is computed in a separated function defined in an anonymous
namespace
=> Add getResidualError methods to ErrorMinimizer

CMakeLists.txt
(Fixed regression introduced with 1066b29d61e1f55abd93c8e3cf.)
=> Public headers get installed again into ${INSTALL_INCLUDE_DIR}/pointmatcher.

doc/Compilation.md, doc/Datafilters.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

CMakeLists.txt
This should not be merged before #203 , to stay friendly to client packages that do not have c++11 enabled.
=> Enable c++11 for libpointmatcher itself (addressing #202)

CMakeLists.txt
This is how one can amend the prefix list for find_package.
This should help compiling #217 .
=> Fixed usage of the LIBNABO_INSTALL_DIR variable

pointmatcher/OutlierFiltersImpl.cpp
Since https://github.com/ethz-asl/libnabo/pull/79 the invalid index is no longer `0`. 
This revealed that libpointmatcher was actually using (IMO) invalid matches as if they were matches with the first entry. (see #228 ).
Currently this is only a start fixing this: It affects more than just this line. And my fix is probably not the best.
@bochen87, if you are still motivated to help: could you test this branch together with libnabo master?
=> Avoid using invalid matches

pointmatcher/ErrorMinimizer.cpp, pointmatcher/PointMatcher.h
When making these error minimizer objects a copy of the source data points is made.  If the number of source points is large and then making this copy can be really expensive.  Since these are passed by const value they can be passed by const reference to remove the copy.
=> Changed pass by const value to pass by const reference to remove the extra copy.

CMakeLists.txt, doc/CompilationWindows.md
- Parse version using CMake rather than `grep`, makes it easier for Windows people.
- Removed `grep` install step from windows instructions.
- Renamed `PROJECT_VERSION` to `POINTMATCHER_PROJECT_VERSION`.
- Deal with CMP0048 by getting the project version first before `project(libpointmatcher)`.
I grepped around for `grep` and didn't see any other place, but maybe it is used for something more?
=> remove `grep` dependency, parse version with CMake

doc/Datafilters.md
- Voxel sizes parameters of `VoxelGridDataPointsFilter` previously in _]-inf;+inf[_ range, so change the documentation to be in _]0;+inf[_ correct range
- Dead link in SurfaceNormalFilter documentation has been removed
=> Fix some errors in DataFilters documentation

pointmatcher/DataPoints.cpp, pointmatcher/DataPointsFilters/Elipsoids.cpp, pointmatcher/DataPointsFilters/Gestalt.cpp, pointmatcher/DataPointsFilters/OctreeGrid.cpp, pointmatcher/DataPointsFilters/OctreeGrid.h, pointmatcher/DataPointsFilters/SamplingSurfaceNormal.cpp, pointmatcher/DataPointsFilters/SurfaceNormal.cpp, pointmatcher/DataPointsFilters/utils/octree.h, pointmatcher/DataPointsFilters/utils/octree.hpp, pointmatcher/DataPointsFilters/utils/utils.h, pointmatcher/PointMatcher.h, utest/ui/DataFilters.cpp
I took into account the reviews from the previous PR about the octree #250 :
- The octree is now templated on the dimension (`dim=3` for the [Octree](https://en.wikipedia.org/wiki/Octree) (3D) case; `dim=2` for the [Quadtree](https://en.wikipedia.org/wiki/Quadtree) (2D) case)
- No more code duplication. Only one `build` function that handle parallel build and with merged stop criterion
- The struct `XYZ` has been replace by `Eigen::Matrix<T,dim,1>` to avoid duplication
- The use of macro has been replaced by functions (ex: `toData`, overload of `idx`)
- `std::thread` has been replaced by `std::async` with `std::launch::async` policy
The new implementation natively support the 2D case with the Quadtree (i.e. a `Quadtree` is an `Octree_<T,2>`).   (fixes #251) 
I created the following …
=> Major revision of the Octree class

CMakeLists.txt, pointmatcher/Bibliography.cpp, pointmatcher/DataPointsFilters/NormalSpace.cpp, pointmatcher/DataPointsFilters/NormalSpace.h, pointmatcher/DataPointsFilters/OctreeGrid.cpp, pointmatcher/DataPointsFilters/OctreeGrid.h, pointmatcher/DataPointsFiltersImpl.h, pointmatcher/Registry.cpp, utest/ui/DataFilters.cpp
During my experiments I remarked that using centroid can lead to false results in the ICP registration. In deed, the centroid is not guaranteed to be a point of the cloud, which induce a new spatial representation and so an offset in the registration.
So, I introduced the concept of _Medoid_, which here is the nearest point from the centroid. Building the sampling point as this ensures that the point is in the point cloud.
As illustrated by the following: 
at the top, we have the results for the _medoid_ method
at the bottom, we have the results for the _centroid_ method
Both produce a similar sampled point cloud, but looking closer we can see that:
- In the top-right corner, sampled points are contained in the original point cloud
- In the bottom-right corner, sampled points are out of …
=> Add a new sampling method for Octree Grid filter based on "medoid"

CMakeLists.txt, pointmatcher/DataPointsFilters/NormalSpace.cpp, pointmatcher/DataPointsFilters/NormalSpace.h, pointmatcher/DataPointsFiltersImpl.h, pointmatcher/Registry.cpp, utest/ui/DataFilters.cpp
I added a new filter feature based on Normal Space Sampling (NSS) from _S. Rusinkiewicz and M. Levoy, “Efficient Variants of the ICP Algorithm,” in Proceedings Third International Conference on 3-D Digital Imaging and Modeling, 2001, pp. 145–152_. 
----
The algorithm works as follow:
1. Construct a set of buckets in the normal-space (stocked in a `std::vector`) 
1. Then put all points of the data into buckets based on their normal direction; 
1. Finally, uniformly pick points from all the buckets until the desired number of points is selected.
**Remark:** a point is randomly picked in a bucket that contains multiple points. 
**Remark:** the uniform sampling is based on a standard Mersenne twister engine
---
As the normals are supposed normed, the _n_-space can be represented by polar …
=> Add new filter based on Normal Space sampling

doc/Datafilters.md, pointmatcher/DataPointsFilters/NormalSpace.cpp, utest/ui/DataFilters.cpp
(fixes #260)
As addressed by #260, the `NormalSpaceDataPointsFilter` trigger an assertion in debug mode due to unsupported 2D point cloud.
Temporary marked the filter as not supporting the 2D case:
- add check for point cloud dimension in filter
- remove 2D test case
**TODO:** add 2D support by building an histogram of 2D normals and uniformly sampling in it.
=> Quick fix for 2D test case in NormalSpace filter

CMakeLists.txt
Closes #266 
Added missing install in order to fix this error:
```
Errors     << libpointmatcher_ros:make /home/wavelab/catkin_ws/logs/libpointmatcher_ros/build.make.002.log
In file included from /home/wavelab/catkin_ws/src/ethzasl_icp_mapping/libpointmatcher_ros/include/pointmatcher_ros/point_cloud.h:4:0,
from /home/wavelab/catkin_ws/src/ethzasl_icp_mapping/libpointmatcher_ros/src/point_cloud.cpp:1:
/usr/local/include/pointmatcher/PointMatcher.h:62:33: fatal error: DeprecationWarnings.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/pointmatcher_ros.dir/src/point_cloud.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/wavelab/catkin_ws/src/ethzasl_icp_mapping/libpointmatcher_ros/include/pointmatcher_ros/transform.h:4:0, …
```
=> Added DeprecationWarnings.h to install

pointmatcher/ICP.cpp
Add validation for the input transformation matrix. Its shape must respect the DataPoint's dimensions.
For some reason, inputing a 4x4 initial tf matrix with a 2D DataPoints (3xN matrix) does not crash libpm. Eigen seems to be able to do a matrix multiplication between a matrix 3x3 and a matrix 4x4! This line should crash:
```c++
// Reajust reading position: 
// from here reading is express in frame <refMean>
TransformationParameters T_refMean_dataIn = T_refIn_refMean.inverse() * T_refIn_dataIn;
```
=> Add validation for the input transformation matrix. 

README.md, doc/ApplicationsAndPub.md, pointmatcher/Bibliography.cpp
Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old links with the `dx` subdomain continue to work, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation by applying this update to all static DOI links and any code that generates new DOI links.
Cheers!
=> Hyperlink DOIs to preferred resolver

pointmatcher/ErrorMinimizers/PointToPlane.cpp
The old version did not return the correct residual:
Instead of 
where r is the residual, w is the weight, e is the delta between the points and n is the normal.
=> Fix point2plan error residual

pointmatcher/ICP.cpp, pointmatcher/PointMatcher.h, pointmatcher/TransformationCheckersImpl.cpp, pointmatcher/TransformationCheckersImpl.h
Hi,
This is a (very late) followup of #163.
I just came back to use libpointmatcher again and I still need to know if my ICP stopped because it reached the maximum number of allowed iterations or not. Since my previous solution was not accepted, I came about with a simpler one that adds an interface where the user can ask if we reached the limit of iterations. I still use an exception internally to be able to flag the limit being reached, but this is not propagated to the one calling the ICP method. This way we avoid breaking code using libpointmatcher.
I don't think there was any other input about the information users need (neither on #163 nor #23). On my side I just need this info, so I can avoid shipping a modified version of libpointmatcher along with my code. :smile: I would be glad …
=> [feature] Add interface to inform if we reached the maximum number of allowed iterations

doc/CompilationWindows.md
Removed libnabo workaround from Windows compilation tutorial because problem is fixed.
=> Removed libnabo workaround from Windows compilation tutorial

pointmatcher/DataPointsFilters/NormalSpace.cpp
Improves the speed of Normal Space binning and selection.
Use a more efficient sampling method instead of rejection sampling. Improves runtime speed and determinism by not attempting to sample low probability events. Remove empty bins and randomly select from only the remaining available bins. Points are added into each bin initially in a random order, and are now popped off the back of a list of points inside the bucket.
=> Improve speed of Normal Space filtering

pointmatcher/DataPointsFilters/CovarianceSampling.cpp
This was a bug, right?  :-)
We cannot write into `Vector3` [3].
=> Fix out-of-bounds access

pointmatcher/ErrorMinimizers/PointToPlaneWithCov.h
#378 added a `force4DOF` param to PointToPlane error minimizer. This param also needs to be added to PointToPlaneWithCov.
=> Add missing force4DOF param to PointToPlaneWithCov

doc/ICPWithoutYaml.md, doc/Transformations.md, examples/icp_customized.cpp
Fix issue #409
Converted raw pointers to shared pointers.
=> Fixed the differences between examples and documentation (#409)

CMakeLists.txt
I added [pthread](https://computing.llnl.gov/tutorials/pthreads/) to the list of external libraries that libpointmatcher links against.
This usually fixes pthread linking issues for other packages. Do note that I haven't been able to reproduce this on my PC.
@peci1 @lucaBartolomei You reported linking issues with pthread before, can you verify that this PR solves your issue?
=> Link against pthread

pointmatcher/DataPointsFilters/utils/sparsetv.hpp
Following the [issue 420](https://github.com/ethz-asl/libpointmatcher/issues/420).
=> Include iso646.h to add `and`, `or`, `not` macros

CMakeLists.txt, libpointmatcherConfig.cmake.in
- Fixes the pthread dependency as discussed in #428 
- Fixes the boost dependency declaration in libpointmatcherConfig.cmake.in so the users won't have to declare it in their project.
I also have a bug, that says that `yaml-cpp-pm-targets.cmake` cannot be found, and I have to manually copy it from `/build/contrib/yaml-cpp-pm/CMakeFiles/Export/share/libpointmatcher/cmake/` to `./build` but I couldn't find how to fix it. 
Fixes #435
=> Fixes for windows

doc/DataFilters.md, pointmatcher/DataPointsFilters/MaxQuantileOnAxis.cpp, pointmatcher/DataPointsFilters/MaxQuantileOnAxis.h
This is an option on the maxQuantilePointsFilter to keep the points beyond or **under** the limit.
=> RemoveBeyond option for the maxQuantileDistance filter

pointmatcher/DataPointsFilters/SamplingSurfaceNormal.cpp, pointmatcher/DataPointsFilters/SurfaceNormal.cpp
There was a bug in the computation of the covariance matrix, which had an impact in the eigen values and eigen vectors computation.
In the `SurfaceNormals` filter: the covariance matrix needed to be divided by `realKnn`.
In the `SamplingSurfaceNormals` filter: the covariance matrix needed to be divided by `colCount`.
Credits go to @pomerlef.
=> Fix the surface normals datapoints filter covariance matrix bug

pointmatcher/TransformationsImpl.cpp
This PR adds the eigen vectors to the descriptors that need to be transformed in the `RigidTransformation` and `SimilarityTransformation` methods, because it was not the case when they were present in the descriptors. This was causing issues when trying to visualize them and working with them.
=> Apply the transformation to eigen vectors

pointmatcher/DataPointsFilters/utils/utils.h
The eigen vectors were serialized row major instead of column major, which shouldn't be the case since everything else is ordered column major in `libpm`. So, it should be assumed that it's also the case for the eigen vectors. This PR will have an impact the users using the following filters:
- [`Ellipsoids (1)`](https://github.com/ethz-asl/libpointmatcher/blob/2ddeb643e8819c137e8e974ff5519a1cdb7014c9/pointmatcher/DataPointsFilters/Elipsoids.cpp#L376), [`Ellipsoids (2)`](https://github.com/ethz-asl/libpointmatcher/blob/2ddeb643e8819c137e8e974ff5519a1cdb7014c9/pointmatcher/DataPointsFilters/Elipsoids.cpp#L379)
- [`Gestalt (1)`](https://github.com/ethz-asl/libpointmatcher/blob/2ddeb643e8819c137e8e974ff5519a1cdb7014c9/pointmatcher/DataPointsFilters/Gestalt.cpp#L536), [`Gestalt …
=> Change storage ordering of the eigen vectors descriptors

doc/DataFilters.md, pointmatcher/DataPointsFilters/MaxPointCount.cpp
fixes #463
Like mentioned in the issues #463, this is the fix that I'm proposing in order to get better and more consistent results with the filter.
Here's a video showing the results:
[Fixed results video](https://youtu.be/m9oe-D1ZHY4)
=> Fix weird behavior of MaxPointCountDataPointsFilter

pointmatcher/DataPointsFilters/MaxPointCount.cpp
=> Windows: Fix Narrowing conversion of seed in MaxPointCount

pointmatcher/Histogram.cpp
Currently all values added to a histogram are sorted before being written to a csv file, but I need the values to be written in the order in which they were added.   
All histogram value are written in a stream at 
https://github.com/ethz-asl/libpointmatcher/blob/17aa1c10f39c90c896333a5d1750e34da7b43ae8/pointmatcher/Histogram.cpp#L80 
However, `computeStats()` is caled just before and do a `std::nth_element()` on the histogram, so it becomes sorted.
I suggest calculating the median, upper and lower quarter on a copy of the histogram, so the original is not sorted.
=> Histogram<T>::computeStats() without sorting the Histogram

package.xml
This prevens rosdep resolving in ROS2
=> catkin not required for pure cmake packages

pointmatcher/ErrorMinimizers/PointToPlane.cpp
I encountered a bug where PointToPlane error minimizer crashes when using `force4DOF` is enabled and the point clouds have very little overlap. Using Debug version of libpointmatcher the crash happens with all point clouds. 
I traced the issue down to this matrix multiplication `matrixGamma*mPts.reading.features`,  where `matrixGamma` and `mPts.reading.features` are 3x3 and 4xN matrices, respectively. Using inhomogeneous coordinates for the points fixed the issue.
stacktrace:
```
main: /home/kaatr/dev/vio/target/3rdparty/host/include/eigen3/Eigen/src/Core/CwiseBinaryOp.h:110: Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::CwiseBinaryOp(const Lhs&, const Rhs&, const BinaryOp&) [with BinaryOp = Eigen::internal::scalar_product_op<double, double>; LhsType = const Eigen::Transpose<const …
```
=> Fix 4DoF PointToPlane error minimizer crash

doc/CompilationPython.md
* Add commands for systems with multiple versions of Python
* Explicitly specify that we use Python 3.6 when installing `pytest` and when building `pybind11`
* Code block for creating a venv when appropriate
=> Add more details in pypointmatcher's installation docs

pointmatcher/DataPointsFilters/SamplingSurfaceNormal.cpp
The sampling surface normal filter didn't remove time values corresponding to points removed by the filter. The resulting point cloud thus contained data items of different cardinality and caused a failure when reloaded in libpointmatcher or paraview.
=> Fix time values after applying Sampling surface normal filter

CMakeLists.txt
An alternative would be to set libnabo_INCLUDE_DIRS and libnabo_LIBRARIES in `libnabo-targets.cmake`
=> Handle libnabo config mode

build_system/.env, build_system/function_library/terminal_splash.bash
- Configure the `build_system/.env` to point to the `ethz-asl/libpointmatcher` repository
- ﹅→ Fix NorLab splash-screen console print issues: invisible on white background, google chrome bad display
- fixed the character color to be set by the OS: white or black base on background
- quick hack to work around the Google Chrome bad display of braille character
- added option type of NorLab splash screen: small, negative and big
=> build-system minor mod

pointmatcher/InspectorsImpl.cpp
The _omega_ descriptor was not listed and, therefore, not exported while saving a compressed point cloud.
=> Fix omega descriptor export

utest/ui/Transformations.cpp
When compiled in debug, two Transformation tests were failing due to an invoked assertion test on this [line](https://github.com/norlab-ulaval/libpointmatcher/blob/e146a503c4f39160ce103bd4fba4f2ed404ef123/pointmatcher/TransformationsImpl.cpp#L195). I replaced the tested data structure for a 2D point cloud.
=> Fix 2D transformation tests in debug

CMakeLists.txt, doc/DataFilters.md, examples/CMakeLists.txt, examples/data/add_descriptor_config.yaml, pointmatcher/DataPointsFilters/AddDescriptor.cpp, pointmatcher/DataPointsFilters/AddDescriptor.h, pointmatcher/DataPointsFiltersImpl.h, pointmatcher/Parametrizable.h, pointmatcher/Registrar.cpp, pointmatcher/Registrar.h, pointmatcher/Registry.cpp, python/CMakeLists.txt, python/datapointsfilters/add_descriptor.cpp, python/datapointsfilters/add_descriptor.h, utest/ui/DataFilters.cpp, utest/ui/IO.cpp
This DataPointFilter adds a new descriptor with a given **name**, **dimension**, and **values** to the point cloud on which it is applied. It can be used, for example, when a map-building algorithm requires the scans to have the same descriptor as the existing map.
=> New DataPoints filter for descriptor augmentation

CMakeLists.txt, doc/CompilationMac.md, libpointmatcherConfig.cmake.in, package.xml
This commit contains the following changes:
1. Fix the issue when `libnabo` is not linked properly and executables using `libpointmatcher` are not built (see https://github.com/norlab-ulaval/libpointmatcher/issues/526). Tested on both the [HEAD](https://github.com/norlab-ulaval/libnabo) and [1.0.7](https://github.com/norlab-ulaval/libnabo/releases/tag/1.0.7) of `libnabo`.
2. Set the supported version of `yaml-cpp` on MacOS to [0.7.0](https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.7.0) and edit the documentation accordingly.
3. Modify CMakeLists.txt to make use of the [CMakePackageConfigHelpers](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html)
=> Fixes to CMake library management config generation

CMakeLists.txt
CMake 3.10.2 is the default version on Ubuntu 18, so it's the minimum version we should require.
=> Update the minimum required Cmake version to 3.10.2

CHANGELOG.rst, package.xml
Do a release of 1.4.1 for libpointmatcher
The source release of 1.4.0 was done on this repository without bumping the package.xml version. This means that that version cannot be released on the ROS 2 buildfarm to fix https://build.ros2.org/view/Rbin_uN64/job/Rsrc_uN__libpointmatcher__ubuntu_noble__source/
Instead of moving the tag or any other git shenanigans, just make a new release 1.4.1 that properly updates the CHANGELOG and bumps the package.xml. Once this is merged in, I'll need one of the maintainers to also create a tag (1.4.1), at which point we can bloom-release this and fix the build on the ROS 2 buildfarm.
- 1.4.1 release
---
- [N/A] I have made corresponding changes to the documentation 
(i.e.: function, class, script header, README.md)
- [N/A] I have commented …
=> Release 1.4.1

pointmatcher/DataPointsFilter.cpp, pointmatcher/ICP.cpp, pointmatcher/PointMatcher.h
I opened the API to load YAML files so that a configuration can also be created from a node, not just a stream.
This effort is to prepare `libpointmatcher` for the upcoming changes in the configuration of the `norlab_icp_mapper`. Check [this PR.](https://github.com/norlab-ulaval/norlab_icp_mapper/pull/15).
- add a function that loads DataPointsFilters from a YAML::Node object
=> Load DataPointsFilters config from a YAML::Node object

pointmatcher/IO.cpp
Addresses https://github.com/norlab-ulaval/libpointmatcher/issues/574
- Replaced deprecated `boost::filesystem::complete` with `boost::filesystem::absolute`
- Replaced deprecated `boost::filesystem::extension(path)` with `path.extension().string()`
- Added a check if a filename contains an extension
=> Fix failing build due to deprecated boost::filesystem functions

pointmatcher/PointCloudGenerator.cpp
My build was failing with clang 18.1.3
```
error: non-constant-expression cannot be narrowed from type 'double' to 'ScalarType' (aka 'float') in initializer list [-Wc++11-narrowing]
173 |         const ScalarType radiusSample{ radius * sqrt(uniformDistribution(randomNumberGenerator)) };
```
By inserting a `static_cast` it fixed it
=> Fix compile error with clang

build_system/lpm_utility_script/lpm_bashrc_config.bash, build_system/tests/tests_docker_interactive/build_and_run_IamBuildSystemTester.bash, build_system/ubuntu/entrypoint_special_cases/entrypoint_execute_lpm_unittest_conditionally.bash, build_system/ubuntu/lpm_execute_libpointmatcher_unittest.bash, build_system/ubuntu/lpm_install_dependencies_general_ubuntu.bash, build_system/ubuntu/lpm_install_dependencies_libnabo_ubuntu.bash, build_system/ubuntu/lpm_install_doc_dependencies_ubuntu.bash, build_system/ubuntu/lpm_install_libpointmatcher_ubuntu.bash, libpointmatcher_dependencies_installer.bash, libpointmatcher_installer.bash
**refactor: prefix functions with n2st namespace**
- Renamed functions to include the `n2st` namespace for consistency.
- Updated script header and footer printing functions.
- Aligned warning and error message functions for uniformity.
- Ensured splash screen functions reflect the new naming convention.
**build: update N2ST and NBS submodule to latest**
- Updated N2ST and NBS submodules to their latest versions for improved stability and feature set.
---
(i.e.: function, class, script header, README.md)
(Check [contributing_instructions.md](/doc/contributing/contributing_instructions.md) for local testing procedure using _libpointmatcher-build-system_)
(the _build-system_ won't be triggered otherwise)
(the _build-system_ will reject it otherwise)
(See …
=> Update submodule to latest and update N2ST fct call with new prefix

build_system/.env.build_matrix.dependencies, build_system/.env.build_matrix.libpointmatcher, build_system/.env.build_matrix.libpointmatcher.bleeding, build_system/.env.build_matrix.libpointmatcher.release, build_system/docker-compose.dependencies.yaml, build_system/docker-compose.libpointmatcher.yaml, doc/LinkingProjects.md
**fix: solve master and dev scheduled build instability**
- Modify Docker compose files to enforce full rebuild for all builds.
- Adjust Docker image architectures and add cache control.
- Update version in .env build matrix files from 1.4.2 to 1.4.3.
- Update LinkingProjects documentation to reflect new version.
- Issue NMO-589
**Merge pull request #576 from norlab-ulaval/release**
- Merges changes from the release branch to the main branch, ensuring all development changes are incorporated.
These commits address build instability issues in the master and dev branches by enforcing a full rebuild for all builds, adjusting Docker image architectures, and updating various files and documentation to ensure consistency and reliability.
---
(i.e.: function, class, script header, README.md) …
=> fix: solve master and dev scheduled build instability
