norlab-ulaval/libpointmatcher

CMakeLists.txt

Reverts ethz-asl/libpointmatcher#68

Revert "completed the linking of the shared library"

---

doc/TransformationDev.md

registrar.cpp --> Registry.cpp

Small fix to docs

---

pointmatcher/DataPointsFiltersImpl.cpp
pointmatcher/DataPointsFiltersImpl.h
pointmatcher/Histogram.cpp
pointmatcher/ICP.cpp
pointmatcher/IO.cpp
pointmatcher/InspectorsImpl.cpp
pointmatcher/PointMatcher.h
utest/ui/IO.cpp

Tested in Ubuntu 14.04 with ROS Indigo for comparison with DRL system:
https://github.com/carlosmccosta/dynamic_robot_localization_tests/blob/hydro-devel/launch/environments/asl/bags/ethzasl_kinect_dataset_high_complexity_slow_fly_movement.launch
roslaunch dynamic_robot_localization_tests ethzasl_kinect_dataset_high_complexity_slow_fly_movement.launch use_dynamic_robot_localization:=0 use_ethzasl_icp_mapper:=1
To integrate with ROS Indigo ethzasl_icp_mapper i had to compile with:
git clone git@github.com:carlosmccosta/libpointmatcher.git
mkdir libpointmatcher_build && cd libpointmatcher_build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo ../libpointmatcher
make
sudo make install

Added RandomSampling filter from PCL. Fixed loading ply files with color information. Improved Histogram stats.

---

CMakeLists.txt

I don't think these lines are doing anything. 
Other opinions?

Removed dead cmake code

---

CMakeLists.txt
pointmatcher.pc.in

The library output wasn't right.

Some improvements for the pkg-config output

---

pointmatcher/DataPointsFiltersImpl.cpp
pointmatcher/TransformationsImpl.cpp

Removed some unused expressions.

Fixed warnings previously introduced

---

evaluations/official_solutions/Chen91_pt2plane.yaml

I found a yaml file which no longer satisfies the existing syntax. I put a fix. I set knn to 10, as that's what is mostly used in other yaml files.

Fix for a no-longer valid yaml file

---

README.md
doc/Introduction.md
doc/index.md

I expanded the README by explaining what ICP is, and added an introduction section giving a preview of what libpointmatcher is about with links to relevant sections.

Doc expansion

---

examples/icp.cpp

This turns on the warning stream (to `stderr`). It also adds a `--verbose` option additionally turning on the info stream.

Made pmicp more verbose (enabled logging to std output)

---

pointmatcher/ErrorMinimizersImpl.cpp

Fixed issue #181.

---

pointmatcher/IO.cpp
pointmatcher/IO.h

This should resolve the issue #182. It also cleans unused variable.

added intensity to the list of supported descriptor

---

pointmatcher/DataPointsFiltersImpl.cpp
utest/ui/ErrorMinimizers.cpp

clean compilations warnings

---

pointmatcher/ErrorMinimizersImpl.cpp

handle reflexion in PointToPointWithCovErrorMinimizer

---

examples/compute_overlap.cpp
pointmatcher/DataPointsFiltersImpl.cpp
pointmatcher/ErrorMinimizer.cpp
pointmatcher/ErrorMinimizersImpl.cpp
pointmatcher/InspectorsImpl.cpp
pointmatcher/MatchersImpl.cpp
pointmatcher/OutlierFiltersImpl.cpp
pointmatcher/PointMatcher.h

This is a replacement of #229  (I've accidentally pushed to master effectively merging it; and undoing that does not reopen the PR..)
(addressing #228)

Avoid using invalid matches

---

pointmatcher/DataPointsFiltersImpl.cpp
pointmatcher/DataPointsFiltersImpl.h

- add `const` qualifiers where needed  
- change from postfix to prefix (`i++` to `++i`)
- set variables for loop stop condition
- adapt brace style to convention

Fix/datafilters : clean Data Filters before reorganizing them

---

utest/ui/Outliers.cpp

Forgot to add it to my previous PR.

Add UT for VarTrimmed

---

README.md
doc/ApplicationsAndPub.md
doc/ApplyingDataFilters.md
doc/BasicRegistration.md
doc/CompilationMac.md
doc/CompilationUbuntu.md
doc/CompilationWindows.md
doc/Configuration.md
doc/DataFilters.md
doc/DataPointsFilterDev.md
doc/DefaultICPConfig.md
doc/ICPIntro.md
doc/ICPWithoutYaml.md
doc/ImportExport.md
doc/Introduction.md
doc/LinkingProjects.md
doc/PointClouds.md
doc/TransformationDev.md
doc/Transformations.md
doc/UnitTestDev.md
doc/UsingInRos.md
doc/index.md
mkdocs.yml

See issue #383.
Note that the changes made have been tested with `mkdocs` version 1.1.2.

[WIP] Fix/typo : Tutorials improvements

---

.readthedocs.yml
doc/DataPointsFilterDev.md
doc/requirements.txt
mkdocs.yml

Fixes tutorials formatting problem (#373)

---

pointmatcher/Registrar.h

Also replaced the boost.auto macro with the C++11 auto.

Replaced the remaining raw pointers with shared pointers in Registrar.h

---

README.md
doc/CompilationMac.md
doc/CompilationUbuntu.md
doc/CompilationWindows.md
doc/Configuration.md
doc/DataFilters.md
doc/LinkingProjects.md
doc/index.md
mkdocs.yml

Plus a few other minor corrections and changes to the documentation

Reorganization of the compiling tutorials for ubuntu and macos

---

pointmatcher/DataPointsFilters/Sphericality.cpp

The keyword "or" is not supported by windows compilers.

---

pointmatcher/Matches.cpp
pointmatcher/OutlierFiltersImpl.cpp

This PR aims to make the convergence error messages from the Matches and OutlierFilters classes a bit more informative.

[Matches/OutlierFiltersImpl] Made convergence error messages more informative

---

package.xml

In line with https://github.com/ethz-asl/libnabo/pull/119

package format=3

---

LICENSE

Same as https://github.com/ethz-asl/libnabo/pull/118

Create LICENSE file based on BSD license as per package.xml

---

pointmatcher/DataPointsFilters/SurfaceNormal.cpp

The inner loop counter variable at line 205 is updated to " j " .

Updated the inner loop counter 

---

build_system/readme_test.md

test docker daemon data-root relocation to external drive

Update readme_test.md for docker daemon test
